// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUm0mmN44qabV2Ij8wosWwRHfL3A2UuSI',
    appId: '1:934157333335:web:0826e65c514cdaed070412',
    messagingSenderId: '934157333335',
    projectId: 'sm3ly-306ea',
    authDomain: 'sm3ly-306ea.firebaseapp.com',
    storageBucket: 'sm3ly-306ea.appspot.com',
    measurementId: 'G-9E7J6V11ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1MARnmcl1dBuRVvDaowJhUgeZoPg3jv4',
    appId: '1:934157333335:android:cabb7f5f379770c6070412',
    messagingSenderId: '934157333335',
    projectId: 'sm3ly-306ea',
    storageBucket: 'sm3ly-306ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMuKi0udq1eSOqvDveNRnLxU4kJniVNI',
    appId: '1:934157333335:ios:d3cb785513d801fe070412',
    messagingSenderId: '934157333335',
    projectId: 'sm3ly-306ea',
    storageBucket: 'sm3ly-306ea.appspot.com',
    iosClientId: '934157333335-ku5vh6q349ql40td1nfucc1b9pitnbns.apps.googleusercontent.com',
    iosBundleId: 'com.example.sm3ly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIMuKi0udq1eSOqvDveNRnLxU4kJniVNI',
    appId: '1:934157333335:ios:08866554ef777214070412',
    messagingSenderId: '934157333335',
    projectId: 'sm3ly-306ea',
    storageBucket: 'sm3ly-306ea.appspot.com',
    iosClientId: '934157333335-bqp6jl0k0r0t0mkr8qtlpf9n52h82kp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sm3ly.RunnerTests',
  );
}
